---
title: "The Economic Value of Biodiversity in India"
subtitle: "Running Notes"
author: 
    - Raahil Madhok
    - Matt Braaksma
    - Ryan McWay
    - Jovin Lasway
toc: true
format: 
    html:
        theme: sandstone
        html-math-method: katex
        embed-resources: true
        code-fold: true
        code-tools: true
        code-overflow: wrap
    pdf:  
        documentclass: article
        papersize: letter
number-sections: false
# jupyter: python3
# NOTE: Quarto preview will only render the html file
#       To render both html and pdf file run in terminal: 
#       quarto render docs/notes.qmd
---

## Project Description

This project aims to produce the first measure of willingness to pay (WTP) for biodiversity. 
This provides a monetary measure to value biodiversity which can be applied to a wide variety of applications in environmental economics and natural captial accounting. 
The data relies on E-bird observations of diverse bird species observations. 
The sample is limited to local, long-time users who are residents (not tourists) in India.
The methodology to calculate WTP relies on a revealed preference throughh the random utility model (RUM). 
The RUM determines the value of seeking out diverse species of birds by comparing the value of alternative counterfactual bird siting locations and the cost to go to these counterfactuals. 
Monetary value is determined through the RUM by estimating the travel cost of the reveal preference compared to counterfactual locations. 

## Notes

For notes, we present the most recent first so that notes are chronologically most recent. 



::: {.callout-note collapse="true"}
# 12/04/2025

>  Ryan

## Code Review

- Attempted a task by task run for scenario "BM-2y_c5km_v5km_r5km_mInf"
- Updated input data
- Reviewed README, file and data structure
- Reviewed scenarios.yml, utils_config.R, utils_scenarios.R, and utils_tasks.R
- Began individual runs with baseline scenario with run_task() and reviewing code in each task. 

- Script 01:
	- TODO estimating average distance when re-assigning home
	- TODO Table by district of number of re-assignments for off-coast homes.
	- Loading the ebird data is MUCH faster this time (187.6 seconds). Yeah new computer.
	- `Warning: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :automatically selected the first layer in a data source containing more than one.`
	- This warning comes up quite frequently later on.
- Script 02: 
	- Very straight forward. 
	- 10.59 seconds 
- Script 03: 
	- Again, no major change here. 
	- 10.1 seconds
- Script 04: 
	- Definitely new with the Voronoi
	- A bit confused why you need to go from centroids, to polygons, to voronois, back to centroids.
	- 176.81 seconds 
- Script 05: 
	- 105.19 seconds
	- No major changes from before. 
- Script 06: 
	- This is new script to me. 
	- I had the era5_2m_percipitation not `_total_`. Took me a while to download the new total data (about 1 hour)
	- Main function makes sense. Just takes time to run. 
	- 1998.65 seconds
- Script 07: 
	- I wonder if lines 97-99 would be more efficient with fcase() function in DT
	`trip_richness[month %in% c(12, 1, 2), season := "Winter"]`
	`trip_richness[month %in% c(3, 4, 5), season := "Spring"]`
	`trip_richness[month %in% c(6, 7, 8), season := "Summer"]`
	- 170.52 seconds
- Script 08: 
	- New to me. Makes sense the merging and the selection of PA intersection
	- These parquet files are VERY light.
	- 30.99 seconds
- Script 09: 
	- There is still 6.travel_cost.R instead of 09_compute_travel_cost.R
	- Should we delete this script? Does it still have value?
	- This is familiar and has the exchange rate adjustment
	- On line 98, does it make more sense to use param start and end years instead of hard coding 2014 - 2024. Broader point about the use of 2014 for filters later on. 
	`gdp_india <- gdp_all[iso == "IND" & year >= 2014 & year <= 2024]`
	- To be clear, we don't use travel time from 159 in 161. So this is redundant?
    `travel_time_hours = geo_dist / travel_speed_kmph`
	- 3.93 seconds
- Script 10: 
    - This is debatable to change given Raahil's search into logitr
    `wtp_manual <- -coefs / price_coef`
    - 9.67 seconds
    - Could be useful to know the average expected richness. This is a way to interpert the result.
    - For these models, are we able to add clustered standard errors? We can add level of clustering into the params vector
    - I added `robust = TRUE` 
    - Results I got: 

> WTP estimates (basic model):
>                       Estimate  Std. Error  z-value  Pr(>|z|)    
> expected_richness    0.00107252  0.00038516   2.7846  0.005360 **

> WTP estimates (FE model):
>                           Estimate  Std. Error  z-value  Pr(>|z|)    
> expected_richness_dm    0.00107697  0.00038518   2.7960  0.005174 **

> WTP estimates (mixed logit):
>                         Estimate  Std. Error  z-value  Pr(>|z|)    
> expected_richness     1.0716e-03  3.9770e-04   2.6945  0.007049 **

- Script 11: 
    - Nice way to consolidate the output for any given scenario
    - Came up with error trying to produce WTP table 
    `--- Creating WTP comparison table ---`
    `Error running 11_generate_scenario_outputs.R: arguments imply differing number of rows: 7, 0, 1`
    `Error in data.frame(variable = rownames(wtp_values), wtp = wtp_values$Estimate,  :`
    `arguments imply differing number of rows: 7, 0, 1`

- Script 12: 
    - Have not tried to produce this yet as I would like to get script 11 working first. 
:::


::: {.callout-note collapse="true"}
# 11/14/2025

> Raahil, Matt, Jovin, Ryan

# TODO: 

- **Matt**: Attempt robustness checks (vary years, vary experience level)
- **Matt**: Santity check for running robustness checks
- **Jovin**: Focusing on constructing shift (within next two weeks)
- **Ryan**: Re-run Matt's new code structure
- **Ryan**: Explore how mlogit function works
- **Raahil**: Figure out the steps to do the individual WTP


## Agenda

1. Check on GDP
    - GDP (income) was in USD
    - Travel cost was in rupees. per KM cost is 7.5 Rupees
    - So we need an exchange rate conversion to USD
    - GDP values should be 2014. And exchange rate for 2014
2. Updates on Shift development
    - No updates
    - Creating the share for each household
3. [JEEM Paper](https://www.sciencedirect.com/science/article/abs/pii/S0095069617307398) allows us to estimate WTP with only 5% or 10% of counterfactual sample
    - Validates our approach.
4. Matt showed the updated structure
    - Set up so you can change the scenario settings and re-run as much as we want
    - Some sanity checking to complete. 
5. Scenarios
    - Manage size for computer but representative birdwatchers (cannot limit to super birders)
    - 3 types of user: new users, medium users, and experts (recording the break points in the distribution of visits)
        - Could be a line graph (WTP is y axis, parameter value)
        - So this shows how WTP changes as we change the parameter value for any given parameter
    - Vary choice radius for each household. 
        - 5 to 30 alternative choices (driven by finding from JEEM paper)
    - Seasonality model
6. Mixed Logit packet
    - Why are we geting a negative number. 
    - What is going on inside the mlogit packet. 
7. Potential Tasks
    - IV estimate 
    - Individual WTP
    - Welfare estimates

:::



::: {.callout-note collapse="true"}
# 10/30/2025

> Raahil, Matt, Jovin, Ryan

# TODO: 

- **Matt**: Attempt robustness checks (vary years, vary experience level)
- **Jovin**: Check units for GDP >> make travel cost in USD.
- **Jovin**: Focusing on constructing shift

## Agenda

1. Missing expected species richness data:
    - Limit to 5 years and missing species richness reduced to only 33% of sites
        - 2019 -- 2023
    - Dropping if choice where trip or counterfacutal are missing. 
    - Limited coutnerfactual choice set to 30 (helps with convergence of estimates)
    - Dropped trips where there was less than 2 counterfactuals
    - Results produced
        - Fixed effects are not having an effect (odd)
        - signs are correct in utilty space
        - WTP is about .3 ruppees for an additional species
        - Jovin checking if the wage conversion is GDP in rupees not USD.
    - We will do WTP manually
    - Next steps are on quality control. Pinning down a WTP that works and makes sense. 
        - Expand robustness checks for 5 years / 10 years, vary user experience, cluster size
    - Matt will update the workflow
2. Shift share instrument progress:
    - Finished classifying migratory species.
    - Working on constructing shift in the IV. 
        - $\gamma$ is completed
        - Disentangling the avian flu data from India and originating foriegn.
    - Share is completed
    - Can complete by next week's meeting. 
3. IV and endogeneity:
    - What determines utility which is not explained in the utility function. 
        - The observed is species richness and forest cover (landscape factors)
        - Unobserved determinants which may be systematically correlated with species richness and utility which would manifest through travel cost
            - Bradt paper claims with is amenity values of where people live. 
    - Exisiting case: Development effects species diversity and site selection choices. 
        - High biodiversity areas which have high development (deforesting), then cost is affected by environment and the development activities
        - This would lead to bias in the choice decision. 
        - IV only affects species diversity but not local economic development or infrastructure. 
    - Use IV for individual WTP
        - Panel data set of WTP by person over time
        - (1) why does WTP change over time (determinants of WTP) - village characteristics, home attributes, 
        - (2) TBD... 
        - People in greener areas have higher WTP, but places with greener areas attract people with higher WTP
4. Explanation of why CES production function is bad
    - Ryan: Added a snippet into the overleaf document. 
5. Estimating individual WTP
    - Endorsed my Richard Carson
    - Determinants to WTP (why do some people value biodiversity more than others)
    - Outcome is WTP. Explanatory is many determinants
    - This is a better justification for the IV.
:::


::: {.callout-note collapse="true"}
# 10/17/2025

> Raahil, Matt, Jovin

# TODO: 

- **Matt**: experiment with the discussed techniques to decrease the missing data
- **Matt**: estimate WTP after dropping the missing observations
- **Jovin**: Complete the shift-share IV
- **All**: Brainstorm other reasons that location to biodiversity could be endogenous

## Agenda

1. Missing expected species richness data:
    - We reviewed the attached document to better understand the large amount of missing values in the expected species richness variable
        - There are relatively few missing observations for observed trips
        - Most of the missing values occur in the counterfactual trips
    - We discussed how to best deal with the issue
    - Raahil noted that with mixed logit, IIA is not violated. So we can proceed with estimating WTP after dropping the missing values
    - To attempt to reduce the number of missing values, we can
        - subset the time frame to more recent data (last 5 years)
        - decrease the overall number of clusters
        - decrease the restrictions on ebird users
1. Shift share instrument:
    - Jovin has finished matching the birdlife range data to the migration categories
2. IV and endogeneity:
    - Raahil reviewed the lack of endogeneity concerns from the previous meeting
        - One potential source could be road quality

:::


::: {.callout-note collapse="true"}
# 10/10/2025

> Raahil, Ryan, Jovin

# TODO: 

- **Matt**: Figure out missing species diversity issue.
- **Jovin**: Completing migration classification for birds (add details on data sources into Overleaf)
- **Jovin**: Completing the shift-share IV
- **Jovin**: Raahil wants to know % of species are migratory vs resident.
- **Ryan**: Expand on what the endogeneity concern (selection on expection of biodiversity)
- **All**: What are our sources of identifying variation
- **Ryan**: Write up why the model is wrong (CES is bad because (1) no prices/they are public good, (2) cannot purchase -- language of economists does not translate into ecological model)

## Agenda

1. Shift Share Construction: 
- Jovin Update: 
    - Confirming migratory status is creating difficulty in finishing
        - This is for the birds that don't match given the classificaiton that Raahil provided
        - This is for 300 birds with manual classification. 
        - Goal is to complete this by next week.
    - I've worked on matching between bird range polygons and migration status using the Birds of the World database. The classification is now almost ready as species-verified, replacing the earlier ChatGPT-based tagging to ensure consistency across migratory and non-migratory species.
    - For the matching process, I've done -  first matching by exact genus-level matches and finally applying fuzzy matching, adhering to a Jaro-Winkler similarity of greater than 95%, to capture minor spelling variations and naming inconsistencies, which helps resolve most species-level mismatches.
    - On the spatial side, I'm finalizing the one-to-one correspondence between polygons and migration categories. Once this is complete, I'll then jump to start building the shiftt-share IV.
    - Raahil wants to know % of species are migratory vs resident.

2. Value of Biodiversity Paper Review
- Ryan Thoughts: 
    - Strategy: 
        - The model of species increase in period t-1 for ecosystem service value in period t is valuable. I think this is a useful framework for thinking of how species richness change drives tourism recreation for birds with the value coming from biodiversity. Proposition 1 in particular makes this point. 
        - On page 11, the authors point out a weakness of our shift-share: covariate weather/environmental shocks driving the shock to migratory birds. 
        - There shock derives from their theory of ecosystem service value which does have a nice benefit. We could invoke this theoretical motivation for recreation services value in our setting. 
        - Good citations in Section 3.4 for why winter habitat conditions are important. For us, I think we would be stating the opposite (summer conditions) as these birds winter in India. This could be problematic for us. 
        - Mimicking Figure 2 seems important to visualize the connection of the avian flu to specific regions in India.
    - Issues/Improvements: 
        - Their shock to winter conditions in NDVI. This is a bit too broad as it could associate with a whole lot of covariate economic and environmental conditions. Our localized avian flu is far more targeted, I believe. 
        - Also, the NDVI measure is not really a shock (e.g., not +- 2 SD from local average) indicating a local shock. So we make an improvement by using a diesase outbreak which would directly negatively affect bird species. NDVI is unclear to me to hold the monotonicity assumption of an IV. 
- What we like: 
    - Very clear what is the identifying variation 
        - Differences in migration routes
        - Differential timing of Flu outbreaks across species into India
        - Differences within species responding to flu by source country
    - Valuation may be different from diversity vs abundnace
        - If a species is rare then you may not be willing to pay much. 

3. Shift Share Equations
- Completed and in Overleaf now for review

4. Missing Species data issue
- Matt Updates: 
    -  I was trying to understand the coverage by cluster in the data for our time period, so this is not our actual counterfactual panel but rather a day by year cluster panel for the ten years. So Table 5 is showing that coverage for cluster-days, which species richness variables exist in the data. Then table 5 subsets that by looking at only days where observations occurred, and which species richness variables exist in the data.
    - From Table 4 and 5, it seems that some of these hotspots are much more popular than others. Coverage for the observed trips is pretty good; only 3.6% are missing all of the options. However, when including the full panel of cluster days (some of which will be counterfactual trips), the coverage is much worse. 
    - Since this is the cluster panel, I will do this again for the actual counterfactual panel and update. 

5. Endogeneity concern
    - Selection by visitors on expectation of biodiversity
    - Therefore biodiversity is endogenous to travel cost (unobservable characteristics in model leading to selection)
    - Probably not the housing selection as in Bradt (2024)
    - Consider reverse causality concerns. 
    - What we want to think through is what is the bias in either of these $\beta$ which cannot be address with our controls 
    - Potentially sorting. E-bird users in India are rich so could be Bradt moving argument.
    - Things that:  
        - Unobserved about location j
        - Unobserved about user affecting income
        - These things need to operate through travel cost
    - We can draw simple DAG

$$
    WTP = \frac{\beta_{bio}}{\beta_{income}}
$$


:::


::: {.callout-note collapse="true"}
# 9/12/2025

> Raahil, Matt, Ryan, Jovin

# TODO: 

- **Matt**: Diagnositics for missing species richness
- **Matt/Jovin**: Migration component for Shift-share
- **Ryan/Jovin**: Computing Shift-Share
- **All**: Review new working paper (has new IV)

## Agenda

1. Missing information for species richness by season
- Core issue coming from the imputation with BirdLife data leading to negative coefficient
- Several hotspot clusters are missing seasonal information
    - Means that noone is visiting these hotspots previously (e.g., rarely visited)
- Diagnostic: Number of trips per hotspot (confirm they are hotspots)
    - Number of distinct time periods with observations for each hotspot
2. Migration for Shift-share
- Classify birds are migratory or not
- Remove species with missing migratory classification
- Keep migratory species to determine migration connections to regions
- Jovin has successfully matched a lot of these (fuzzy matching)
:::



::: {.callout-note collapse="true"}
# 8/27/2025

> Ryan, Jovin

# TODO: 
- **Matt**: We need to meet with you to discuss working on this with MSI
- **Jovin**: Responsible for Shift
- **Ryan**: Responsible for Share

## Plan to Estimate Shift-Share

1. Merge the Species range data with the migratory species data
    - Species range data: base-data/species/BOTW_2024_2.gpkg
    - Migratory species data: base-data/species/species_list_categorized.csv
    - Merge by: scientific_name
    - Result: species level data with range map and classifier for migratory
2. For each country j, calculate $\gamma_j$

$$
\gamma_j = \sum_{s =\text{total num of species in j}}^S \frac{\text{species range overlap India}_{sj}}{S_j}
$$

- Count the number of species $s$ in $j$
    - Species range data: base-data/species/BOTW_2024_2.gpkg
    - India Borders: data/shp/district-2011
    - Need to make one shape (spatial union) so any intersection with India shape
    - Indicator for each species if any overlap of species with India borders

- Spatial overlap of species $s$ range over the country border of India. This will create some fraction. 
    - Calculate sqkm for India shapefile one time (part 1)
    - Spatial inner join of range $s$ on India. 
    - Calculate sqkm for the inner join (part 2)
    - Divide part 2 by part 1 to get the fraction of overlap for species range over India borders

- Combine to make $\gamma_j$ using the weighted sum $\sum_s$
    - Spatial intersection of species range $s$ with countries in the flu dataset
    - Create the weight $S_j$ by counting the number of indicators for intersecting ranges with $j$
    - Create $\gamma_j$ for each $j$ by summing fractions in (2) divided by weight $S_j$
    - Country $j$ Shapefiles: TODO.

1. Create the shift by merging $\gamma_j$ with the flu data
        - Flu Data: data/clean/flu-data.csv
        - Result is time series by t
$$
Shift_t = \sum_{j = country}^J flu_{jt} \times \gamma_j
$$

1. Create the share for each hotspot t

$$
Share_d =  \sum_s \frac{\text{Indicator for migratory}_{sd}}{S_d}
$$

    1. Start with e-bird data. For each hotspot $d$ get the number of unique species observed in the data
        - e-bird data: Ask Matt what is the best way to do this given the current workflow. 
    2. Merge in the migratory data on these species for each hotspot $d$
        - Migratory species data: base-data/species/species_list_categorized.csv
        - Merge by: scientific_name
    3. Create the share variable as weighted sum for hotspot $d$
        - For hotspot $d$, count indicator for migratory. 
        - For hotspot $d$, get count of unique species $S_d$
        - Then construct sum of the fractions. 

5. Create the IV by multiplying the shift by the share for each hotspot d

$$
IV_{dt} = shift_t \times share_d
$$

:::


::: {.callout-note collapse="true"}
# 8/15/2025

> Ryan, Matt, Raahil, Jovin

# TODO: 
- **Matt**: Demean data for State x month fixed effect and user fixed effects 
- **Matt**: Resolve imputing species richness by estimating correlation of e-bird to bird life data and deflate value
    - **Matt**: Degree of Imputation: Summary stats on % of missing in observed and counterfactual data
- **Jovin**: Constructing the shift-share IV

## Agenda

1. Estimation of WTP
    - negative values came from mismatched polygons
        - Difference from the clipped calipers instead of the original simple circles
    - weeks sometimes were only 53 (not 54). Solved with iso-week formating that allows for more merging of site attributes
2. Data issue
    - we don't observe species richness
    - So we are imputing with range maps
    - When there is missing, we currently fill with species map
    - Possible species ranges is always higher than recorded value from e-birders
    - So the imputed values always are super high when missing, and then this makes our estimates really weird.
        - This penalizes the choice. Because counterfactual choice has huge species richness
    - Potential Solution: replace missing with historical average (or minimum average) for each district or state in the same time period. 
        - Impute that for hotspots with missing data 
    - Potential Solution: correlation of bird life data and e-bird observations
        - Then we can just deflate imputed value that rescales this to the e-bird values
    - What is the main source of missing value? 
        - want summary stats on % of missing in observed and counterfactual data
        - Could make this seasonal species richness for imputed value
3. Fixed Effects Issue
    - NA for standard errors when adding individual fixed effects
    - Running with python on MSI
    - Could attempt to manually demean data (user fixed effects) before running
    - State x month fixed effect and user fixed effects 
        - Robustness by district x month fixed effects 
        - This will just be more intense
    - mlogit does not allow for fixed effects
    - The key is to demean within each group
        - hdfe is package in Stata
4. Instrumental Variables
    - Have a map data for bird migration routes
        - Only found 2 species public for India 
        - There are other species we can request access to
    - Data avaliable for avian flu outbreak
        - H5N1
        - 2005 - 2025
    - Combining the two data sets we can assign outbreaks to specific species that migrate to India
    - Human cases of avian flu deaths should be controlled for in IV estimation
    - If we have a shift-share IV, do we need to know the flyways?
        - If this is the only channel, then we don't need to actually need to know the origin of the bird 

$$
IV_{dt} = shift_t \times share_d
$$

$$
IV_{dt} = \text{Wild Avian Flu}_t \times \text{% of species pool from migration}_d
$$

$$
Shift_t = \sum_{j = country}^J flu_{jt} \times \gamma_j
$$

$$
\gamma_j = \sum_{s =\text{total num of species in j}}^S \frac{\text{species range overlap India}_{sj}}{S_j}
$$

- Assumes a uniform distribution of species across their species range
    - This is an improvement over distance from India as the weight

$$
Share_d =  \sum_s \frac{\text{Indicator for migratory}_{sd}}{S_d}
$$

:::

::: {.callout-note collapse="true"}
# 8/1/2025

> Ryan, Matt, Raahil

# TODO: 
- **Matt**: Re-estimating WTP using new sample of users (expanded)
- **Matt**: Adding a Visual: Attempting to run the simple regression of biodiversity and hotspot visitations
- **Jovin**: Complete the IV design by finding accompanying data. Maps of migration patterns. Papers to cite for this phenomenon.
- **Raahil/Ryan**: Write up the model in LaTeX

## Agenda

1. Figures describing variation 
    - Ryan presented some post estimation figures we tabled for later
    - Matt presented some maps showing variation over space
    - Raahil suggested we produce a margins plots. We run an endogenous TWFE model of species richness on number of visitors. Then we plot the marginal effects at different levels of biodiversity. 
2. First estimates of WTP using super users 
    - Matt is able to run the conditional logit model. Not able to run the mixed logit model
    - Our $\alpha$ for price has the wrong sign. This makes biodiversity WTP a negative value
    - We think that the sample may be too restrictive resulting in weird results 
    - Additionally, Matt is working through some data issues in the counterfactual data set that is dropping 1.1% of site attributes
    - And there is colinearity amongst site attributes when running the conditional logit, so they are currently dropped in the model run. 
3. Modeling updates using IV method
    - Ryan has a clear idea of how to model the IV into our mixed logit model 
    - The key is to rely on Jacob Bradt's model using control functions. 
    - We estimate the first stage linear regression. Residualize. And use the residuals in our discrete choice method (mixed logit). 
    - We will need to bootstrap the 2nd stage in our to recover standard errors. 
4. Bird Migration Instruments
    - (i) Migration patterns: From the literature I've compiled so far:
        - Peak arrivals: August - November
        - Peak departures: February - April
        - Low migration periods: May - July, and December - January
    - The Inbound migration: Birds arrive in India primarily from the northern breeding grounds, especially in Mongolia, Kazakhstan, and Siberia, during the August-November window to overwinter in wetlands and coastal areas.
    - The Outbound migration: Birds depart February-April, returning to their breeding sites for nesting.
    - (ii) Drivers of bird migration and IV framework: Ecology literature indicates that migration along the Central Asian Flyway is mainly driven by (i) Ecological reasons, india's wetlands, lakes, and agricultural landscapes provide abundant food and shelter during winter, (ii) Climatic reasons: Wrmer winter conditions compared to the northern latitudes reduce suruval stress (iii) Stopover importance: Key sites such as Chilika, Keoladeo, Pong Dam, etc serve as staging areas for fueling before onward flights.
    - Recent literature uses environmental shocks as instruments (Noack et al., 2024; Meng et al, 2025). For India's bird migration context, two IV strategies appear promising.
        - Weather shock IV: Baseline district exposure (from our eBird) interacting with NVDI and weather anomalies in the breeding grounds.
        - Disease shock IV: I find this is more interesting because a recent work by Yang et al., 2024 at Nature Communications finds avian influenza outbreaks do not trigger migration but do affect survival and presence of birds at the Indian stopovers to a very large extent. This makes it a credible instrument because: (i) outbreaks are exogenous to the local economic variables and (ii) outbreak timing is tied to a peak of migration window/CAF (Aug-Nov, Feb-Apr) in India, allowing shocks to coincide with relevant bird presence.
    - (iii) Data collection: Potential outbreak data sources, shapefiles include (i) FAO EMPRES-i+; (ii) WOAH/WAHIS, which tracks the outbreak locations, date, disease type, host species, and status. Lastly, GISAID shapefile data, which is an avian influenza sequence database, tracks the outbreak locations (used in Elbe & Buckland-Merrett, 2017, Global Challenges Journal; Yang et al, 2024, Nature Communications).
    - (iv) Next step: Performing a spatial join between outbreak data and our ebird-based hotspots, aggregating outbreak counts to the district/hotspot-year panel level. I think this will allow us to construct the avian influenza IV as = Baseline exposure in district/hotspot d  x outbreak shock at time t.


:::


::: {.callout-note collapse="true"}
# 6/2/2025

> Ryan, Matt, Jovin, Raahil

# TODO: 
- **Matt**: Finish species richness site attribute (cluster-time level)
- **Matt**: Finish computing congestion site attribute
- **Matt**: Check why sample size so big. Check number of elements in the choice set for validation.
- **Matt/Ryan**: Compute species richness in radius *around home* (varying at same time unit as other species richness attribute)
- **Jovin**: Fix travel cost. I suggest checking it over with Matt/Ryan
- **Raahil/Ryan**: Work through paper framing

## Agenda

1. Species Richness 
- Maps for imputation can't have the shannon index. Because we don't have abundance counts
- But we can do an index for the e-bird data hotspots
- Estimates of bird life and expected species richness 
- Monthly values or seasonal values 


2. Other Site Attributes 
- Have one site data set for temp, rain, and tree cover
- This is at the hotspot cluster level 

3. Congestion 
- Ready to go code, just not run yet
- \# of users at hotspot cluster monthly

4. Travel Cost
- Jovin has choice set and code that estmates this for a first attempt 
- Matched to GDP data to impute wages 
- Estimate Euclidean distance between households and hotspot clusters 
- Final data for RUM should be choice set dimensions (for our checks)

5. Measure of Experience at the Individual Level 
- Counts of trips (counter)
- Count for \# of different hotspots (counter)
- So ratio tells us if you have  preference for location ("Habit Formation"). 
    - Low ratio is little location preference
    - High ratio is high location preference

6. Conceptual
- Birds vs. non-bird still valued as travel cost. So both are still measures of nature recreation. 
- Monetizing value >> Add in contribute to GEP or ecosystem service value literature. 
- Novelty: Why is WTP lower in Developing Countries? Welfare for environmental quality in envirodevonomics framework (Env-Dev framing)

:::

::: {.callout-note collapse="true"}
# 5/16/2025

> Ryan, Matt, Jovin, Raahil

# TODO: 
- Seperate meetings for Matt/Jovin (coding) and Ryan/Raahil (conception) for our specializations

## Agenda

1. Finalize the site attribute data and create the master dataset
- Matt and Ryan -- complete by next meeting (May 16)
- We have monthly temperature and rainfall
- We have annual tree cover data
- These are as zonal statistics (average for 10KM radius of hotspot)
    - In E-bird, we have the average distance walked around hotspot
    - Or do we avoid this work because temp, rain, and tree cover does not vary much at such a small spatial scale.
    - Temp, rainfall, and tree are at higher resolutions. So as long as the radius is less than the input data this will not vary. 
- We need to think more about mapping of hotspots and hotspot clusters. 
- Need to add a fourth site attribute: congestion
    - How frequently other users are using this site? 
    - Aggregate number of user trips for each hotspot but will need to do this as a lag (week before)
    - So this is expected congestion. 
- We need to transform this into a panel of counterfactual sets appended to the observed trips. 
    - Not balanced across counterfactual trips and time 


2. Calculate travel costs -- see notes for guidance; this will be added to the site attribute script
- For GDP per capita data, use gridded data from here and extract the value closest to each users' home. Then use the formula from Kolstoe/cameron or lloyd-smith to calculate travel costs. 
- Jovin -- complete by next meeting (May 16)
- Collected 2014-2024 GDP per capita data
- Laptop trouble estimating, working with MPC.
- Could run the travel cost with a small random sample to make this managable for Jovin's laptop capacity.
- Can re-run the pipeline so we are running for only frequent users (1.6M instead of the 3M)

3. Species richness 
- Matt and Ryan -- bring three ideas for next meeting (May 16)
- Close to being done (Matt taking the lead)
- Taking raw e-bird data and getting monthly counts
- Need to translate from hotspots to hotspot clusters
- Species ranges (for missing) shapefiles are crashing the code.
- All of this is to get a species at a hotspot so we can turn this into a richness index 
    - Will want this merged as richness for same month/week from previous year
    - In the app, you can see in real-time species count from their favorite places. 
    - So likely quite responsive. Last week is best
    - Can also do monthly to replicate results from month last year from Kolsto paper method. 
- We aim to use the simpson and shanon index from `vegan` package

4. Individual Attributes
- With individual fixed effects, we partial out any time-invariant
- From the e-bird data:
    - How frequently you went in the past year
    - Average distance traveled in the past year 
    - Is there any measure of learning over time? Value of recreation is not static
        - Experience index
        - Cumulative experience (simple counter of trips up unti that point)
        - Could weight this by how much you walk, and taxonomy of bird level data (raw text file of trip-species level)
        - Could collapse species count to trip level. 

## Project Management

- Meetings need to be in person. 
- Jovin update meeting calendar 
- Start assigning tasks instead of asking for volunteers
- Need to come up with a specialization of tasks. 
- Coding and Data: Matt (lead), Jovin, Ryan (assist)
- Conceptualize: Ryan (lead), and Raahil
    - How our model departs from workhouse. 
    - Literature review for our novelty
- Some tasks: 
    - Google maps driving time
    - inaturalist species richness mapping

:::

::: {.callout-note collapse="true"}
# 5/15/2025

> Ryan, Matt

## Coding Notes
- Ryan is taking lead on estimating travel cost. 
- We need a seperate hotspots shapefile for running zonal stats 
- We need unique hotspot site IDs and hotspot cluster IDs
- Explor alternatives to making hotspot clusters 
- Name for the master data
- Need to add attributes to hotspot clusters (script 4)
- Mapping of hotspot cluster ID to hotspot IDs


:::

::: {.callout-note collapse="true"}
# 5/2/2025

> Raahil, Matt

## Agenda
1. Site attributes data progress
    - In progress
2. Individual attributes data progress
3. Coding sample selection progress
    - Done, flexible to time period and years (e.g. quarterly for at least 8 years)

## Site Attributes

- Still gathering geospatial data
    - [MODIS VCF forest cover](https://lpdaac.usgs.gov/products/mod44bv061/)
    - [Copernicus ERA5-Land](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land?tab=download)
        - [ecmwfr](https://bluegreen-labs.github.io/ecmwfr/), R API interface
- Run zonal statistics on buffer around hotspots
- If data becomes to large to easily share, we can start using Globus and MSI's tier 2 data storage

## Next tasks

1. Merge site and individual attributes to make master dataset
2. Calculate travel cost
    - Start with linear distance for now
    - Calculate cost
        - Refer to Lloyd-Smith and Cameron/Kolstoe
        - Travel cost = 2 (round trip) x distance x 1/3 x wage (from GDP)
3. Species Richness
    - Decide on method: 
        - Weitzman index
        - iNaturalist
        - Simpson index 
        - Shannon index
4. Looking ahead
    - Look at code for estimating mixed logit with big data
        - [mixl](https://github.com/joemolloy/fast-mixed-mnl), C++ based R package
        - [xlogit](https://xlogit.readthedocs.io/en/latest/index.html), GPU-Accelerated Python Package
    - How to properly weight the WTP for aggregation
    <!-- - [Weighting the Evidence: A Rank-Dependent Model of Outdoor Recreation](https://doi-org.ezp1.lib.umn.edu/10.1086/732185) -->
    - Research how to include fixed effects in utility functions (alternative specific constant)
        - User fixed effects 
        - hotspot fixed effects

:::

::: {.callout-note  collapsse="true"}
# 4/25/2025
> Matt, Ryan

## Tasks: 
- Matt: Download data and share
- Ryan: Start writing pseudocode in the new scripts. 
- Both: Play with ClimateR 

## Site Attributes
- Limitation: 
    - It takes time to build GIS data. So a lot of the attributes are not updated for 2024/25
    - ClimateR
- Division of the attributes to collect
    - Protected area (binary or distance) -- fuzzy borders leads to spillovers
        - Matt
        - WDPA (https://www.protectedplanet.net/en/thematic-areas/wdpa?tab=WDPA)
    - Tree cover -- higher willingess to pay for forest
        - Matt
        - https://data.fs.usda.gov/geodata/rastergateway/treecanopycover/
        - https://data.globalforestwatch.org/
        - https://glad.umd.edu/dataset/global-2010-tree-cover-30-m
        - Worse comes to worse we use the ESA data
        - Or we could use NDVI data as a proxy.
    - Rainfall (monthly) - seasonality
        - Ryan
        - https://ftp.cpc.ncep.noaa.gov/GIS/GRADS_GIS/GeoTIFF/GLB_DLY_PREC/
        - CHRIPS SPI data
        - https://mikejohnson51.github.io/climateR/index.html
    - Temperature (monthly) - seasonality
        - Ryan
        - GISS Surface Temperature Analysis (GISTEMP v3)
        - Surface air temperature (no ocean data), 250km smoothing (9 MB)
        - Might need the land mask
        - https://data.giss.nasa.gov/gistemp/
    - Distance to the coast -- species gradient to the coast
        - Ryan
        - Dissolve the districts data. 
        - Make a polyline and measure distance to the nearest line
    - Species richness from the previous week (expectation) -- and any other measures of biodiversity
        - Both Matt and Ryan
        - Weitzmen index using ebird data to generate diversity score
        - https://scholar.harvard.edu/files/weitzman/files/on_diversity.pdf
        - Validate with inaturalist data on birds for india
        - Could test a couple of different indices
- How we are sharing the site attribute data
    - Matt will have the GDrive link. 
- Updating the config files 
    - Once we have data download
- Start script to merge site attributes to sites
    - What to do about 4.demographics. Seems like that should be site attributes. 
    - Noteably, some of the data will need to become panel. 
        - Rainfall
        - Temperature
        - Protected Areas
        - Tree cover
        - species richness (we need to dig some that has a time dimension)
    - Static: 
        - Distance to coast

:::


::: {.callout-note  collapse="true"}
# 4/18/2025
> Raahil, Matt, Jovin, Ryan

## Sample Selection Updates
- different biodiversity levels by incorporating interaction terms in locals and tourists. WTP for nature tourism vs WTP for nature recreation or biodiverstiy
    - If we estimate both, then we can compare both measures. We can also place it within the larger literature of many WTP for both subsets of ecosystem services and the population using those services. 
    - Broadly compare conservation, nature recreation, tourism, or biodiversity 
    - We need to frame this as a development paper as the lambda in the Envirodevonomics paper
- Frequency of observations are consistent over time and potentially visits near protected areas. 
    - Need to capture seasonanlity (time fixed effects)
    - Need to consider some aspect of congestion (can calculate that as a site attribute)
    - If you go two months a year you are less likely to be a tourist

## Literature Review Updates
- We can uses species richness as an explanatory variable in the model. But could add other biodiversity measures beyond bird diversity. 
- Need to think about how to frame this in the developing context instead of the environment context
- Very few WTP for environmental quality in development economics space 
- Would be great if our WTP measure could be placed within a welfare model so we can make counterfactual statements
    - Need to have homogenous agents to aggregate for welfare gains >> e-bird users are not representative of population
    - Could overcome this by population demographic weights to make e-bird users representative
    - But welfare statements are a big improvement over the other e-bird papers
- Could explore the WTP measure of space and time. So we go beyond the cross-sectional estimates in the literature 
    - If we have 1st and 2nd moment, then we can assign individuals an individual WTP. 

## Grant Proposal
- Jovin will provide an update. 

## Initial Results by Raahil 
- We are getting coverage of the country 
- Some overlap of population density and users >> likely representative
- Most hotspots and users are in the south (consistent with e-birder users)
- Hotspots data could be weighted by visits
- Should plot protected areas overlapping hotspots
- Demographic t-test shows e-bird users are richer on average. But we can use this to back out our inverse weight for the welfare calculations
    - E-bird users are selecting into this where there are richer places (so can afford this hobby)

## Tasks
- How do we distinguish ourselves from the Pacific Northwest paper Kolestet 2017
- First pass of the sample: users who use this at least 2 months out of the year
- Make two new scripts: 
    - Merging in site attributes (Can merge in satilette data -- radius around the centriod and take the mean -- and district data about the site attribtues -- merge on district ID)
        - Protected area (binary or distance) -- fuzzy borders leads to spillovers
        - Tree cover -- higher willingess to pay for forest
        - Rainfall (monthly) - seasonality
        - Temperature (monthly) - seasonality
        - Distance to the coast -- species gradient to the coast
        - Species richness from the previous week (expectation) -- and any other measures of biodiversity
    - Estimating the RUM via the mixed multinominal logit
- Email tag for grant proposals
- Make a script into a single PDF

:::

::: {.callout-note  collapse="true"}
# 3/31/2025
> Raahil, Matt, Jovin

## Sample Selection Discussion
- We want to ensure that the sample of ebird observers is representative
    - Remove tourists
    - Remove infrequent users
- Potential strategies 
    - Limit to users that log at least a certain number of times per month
    - Exclude users that post outside of protected areas
    - Exclude users that include tourism tags in text variable(e.g. "ecolodge")

## Tasks
- Matt/Jovin: descriptive analysis on data to determine distributions of frequent users
    - Complete by 4/18

:::

::: {.callout-note  collapse="true"}
# 3/21/2025
> Raahil, Matt, Ryan, Jovin

## Action Items: 

- Everyone confirms that we can run the first 3 basic scripts
- Starting the annotated bibliography with 10 most important papers: 
    - WTP for envrionmental quality 
    - WTP in developing countries using travel cost
    - Review of mixed logit methodology
- Next week we need to talk about sample selection in depth next week 


# Division of Tasks: 
- Review mixed logit method
- (Matt) Review of WTP in developing countries using travel cost methods
- (Ryan) Review of WTP methods for environmental quality
- (Ryan) Method to estimate welfare effects (some exogenous shock)
- (Raahil + Jovin + Matt) Determining the sample population criteria -- important early step
- (Raahil) Gathering data for population demographics (SHRUG, DHS, etc.)


- Ways to annoate bibliography: 
    - paper title + journal,  research question, research design (e.g. stated preference), data/sample size, result (i.e. WTP estimate)
- We need to think about how we contribute. 
- We need to think about sample selection. 
    - Criteria based on usage, overlap with protected areas, etc. 
    - How do we remove tourists? 
    - Who is the average person? Estimates will be sensitive
- Need to gridded map of ebird observations

# Next scripts
4. Merge attributes of the counterfactual sites. Need to collect site level data and/or individual level data 
    - Site attributes: biodiversity, accessibility, ruggedness, congestion, temperature, rainfall, regional developmemnt
    - For first run, just do biodiversity. 
    - Biodiversity comes from either diversity of birds or other attributes of ecosystem diversity
    - Expected biodiversity is why you go. So we can use historical measures of biodiversity
5. Run the mixed logit to estimate the WTP values
6. Welfare analysis of WTP values

:::



::: {.callout-note  collapse="true"}
# 02/28/25
> Raahil, Matt, Ryan

## Action Items: 

- Ryan: Get the correct e-bird file from Matt (DONE)
- Ryan: Merge code files into scripts folder. (DONE)
- Ryan: Initate a document for literature review with template example (DONE)
- We need to specalize and define tasks. Volunteer over email. Tasks: Lit review, sample selection, characterize the sample, theory person (DONE)
- And set up a recurring meeting time. Need a poll. Try for next two weeks from now. (DONE)
- Jovin: Provide your github username so Ryan can make you a collaborator on the github repo.  (DONE)

## Funding: 

- No longer pursue IonE funding

## Coding: 

- Matt was able to replicate everything 
	- Created a YAML to process file names
	- No longer needs new file paths
- Ryan stuck on loading data
- Need to all use the same exact file download for e-bird
- script 1: processes e-bird data, determines user homes, and calculates home for those who don't report it. 
- script 2: Creates the hotspot observations. Measures distance from home to hotspot.
- script 3: Most important. 12,000 hotspots so too many counterfactuals. This script reduces the counterfactual set by clustering hotspots nearby (likley parks) and only consider hotspots within a distance of home. 
- The final data set is a panel of person (user) ID by trip ID appended to all counterfactual trips for this user. 
- When we actually estimate this, we will need to plan for a no-trip counterfactual. 
- One of the main things we need to do is make the computation easier for us. Otherwise it becomes too computationally intensive. 
- Keep all the scripts in scripts folder. 

## Data: 
- We will need to bring in site attribute data 
- So data on landscape measurements. 
- Matt says that not all intermediate files are being save
- Specifically, the master file is not saving
- Need to identify our sample population
	- Need a careful (defensiable) data-driven criteria for sample 
	- Needs to be regular, local users (not temporary or tourists)
	- Determine this based on usage frequency and mobility patterns
	- Consider overlaying protected areas polygons on top of the observations/hotspots
	- Buffers may create a censoring problem. So we would just test this against larger and larger buffers
- Need to find ways to characteristize the users (demographics) without having any information about them. 
	- Important for welfare calculations. 
	- Try to match with DHS data 
	- Or overlap home location with SHRUG data set
	- Econometrically, take attribtues about where they live against the average for the country, how do high and low WTP birders fall within the distribution
	- Potentially use this as weights for welfare calculations. 

## Methods:
- If we get a random shock to bird population, then we can think about the causal effect of increasing biodiversity

## Paper/Writing: 
- For the ML cluster, will want to read up later to find out if there is a better way or more common practice in economics. 
- Create a lit review. Three groups: 
    1. estimates of WTP in developing countries generally using the discrete choice travel cost method (Ted Miguel water quality paper). 
    2. WTP for environmental quality papers and what design they are using to estimate (e.g., contingent valuation, stated preferences -- something from ecology)
    3. Review of any updated versions of the mixed logit model -- new adapations of the model from class
- For this: question, data used, design, and finding (dollar estimates would be great).
- Create a document in the docs folder
:::
